### ISSUE TITLE
Unable to read repository

### ISSUE THREAD

**Issue by awanarwa** [anb0s/eclox#204]
Trying to install Eclox for Eclipse (Neon.3 v4.6.3 ) and I keep getting the error:

org.eclipse/equinox.p2.core.ProvisionException
Unable to read repository at https://github.com/anb0s/eclox/content.xml.
Unable to read repository at https://github.com/anb0s/eclox/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Please help.

**Comment by anb0s** [comment]
Thanks for reporting.

I've just tried the installation of Eclox with Neon.3 and it worked with this sites:
https://anb0s.github.io/eclox
http://anb0s.github.io/eclox

Strange, may be it was GitHub (HTTPS) problem today? Please try the http address...

**Comment by awanarwa** [comment]
Problem persists. Not sure if its because I am sitting behind company firewall? For now I am using doxywizard to generate documentation but I am sure this would have been a nice plug-in to use.

Thanks for you help!

**Comment by anb0s** [comment]
May be it's because of company firewall...

You can download the update site for offline install --> go to: https://github.com/anb0s/eclox/releases
and download the org.gna.eclox.site-X.zip file, e.g. for latest stable version: https://github.com/anb0s/eclox/releases/download/eclox-0.11.2/org.gna.eclox.site-0.11.2-SNAPSHOT.zip

Now use inside Eclipse: "Help-> Install New Software... -> Add... -> Archive...", select the zip file and enter name:
![image](https://user-images.githubusercontent.com/95811/28266004-008a8bfc-6af3-11e7-9569-095445024e0a.png)

and select it:
![image](https://user-images.githubusercontent.com/95811/28266031-2517479e-6af3-11e7-945e-75d85a448630.png)

**Comment by anb0s** [comment]
will close this one, because cannot reproduce and offline install should always work. Please reopen if happens again....

**Comment by anb0s** [comment]
updated README.md with info about offline install
